version: "3"
services:
  api:
    container_name: api
    image: node_api
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    env_file: .env
    environment:
     - NODE_ENV=test
    volumes:
      - .:/usr/src/
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    command: >
      bash -c "npx jest
      --verbose
      --coverage 
      --collectCoverage
      --coverageReporters=html"
  db:
    container_name: db
    image: mongo:4.4
    restart: always
  redis:
    container_name: cache
    image: redis:3.2
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
