version: "3"
services:
  api:
    container_name: api
    image: node_api
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    env_file: .env.development
    restart: on-failure
    volumes:
      - .:/usr/src/
    environment:
     - NODE_ENV=development
     - REDIS_URL=redis://cache
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    command: bash -c "npx ts-node-dev --respawn ./src/index.ts"
  db:
    container_name: db
    image: mongo:4.4
    restart: always
    volumes:
      - mongo-db-data:/data/db
  redis:
    container_name: cache
    image: redis:3.2
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379

volumes:
  mongo-db-data:
